FROM node:14.15-alpine
ENV NODE_ENV development

WORKDIR /app

COPY nx.json package.json npm-shrinkwrap.json ./
RUN npm install -D

COPY tsconfig.base.json angular.json ./
COPY apps/podgroup apps/podgroup
COPY libs libs

CMD npm run start podgroup -- --host 0.0.0.0 --disableHostCheck