version: '3.6'

services:
  
  podmongo:
    container_name: podmongo
    image: mongo

  api:
    container_name: podapi
    build:
      context: .
      dockerfile: apps/api/dockerfile
    ports:
      - 3333:3333
    depends_on:
      - podmongo
    environment:
      DB_HOST: mongodb://podmongo
      DB_NAME: dev
    volumes:
      - './apps/api:/app/apps/api'

  app:
    container_name: podapp
    build:
      context: .
      dockerfile: apps/podgroup/dockerfile
    ports:
      - 4200:4200
    volumes:
      - './apps/podgroup:/app/apps/podgroup'
      - "./libs:/app/libs"
