export const DATA_MODEL = 'DATA_MODEL';
export const DATABASE_CONNECTION_CONFIG = 'DATABASE_CONNECTION_CONFIG';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DATA_MODEL_NAME = 'testdata';